name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t dovsimen/complex -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true dovsimen/complex npm test
 
      - run: docker build -t dovsimen/complex-client ./client
      - run: docker build -t dovsimen/complex-nginx ./nginx
      - run: docker build -t dovsimen/complex-server ./server
      - run: docker build -t dovsimen/complex-worker ./worker
 
      - run: docker push dovsimen/complex-client
      - run: docker push dovsimen/complex-nginx
      - run: docker push dovsimen/complex-server
      - run: docker push dovsimen/complex-worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: complex
      #     environment_name: Complex-env
      #     existing_bucket_name: elasticbeanstalk-us-east-2-157763295732
      #     region: us-east-2
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip